version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      EMOTION_API_URL: http://emotion-api:8000
    depends_on:
      - emotion-api

  emotion-api:
    build:
      context: ./python-emotion-api
    container_name: emotion-api
    ports:
      - "8000:8000"
    env_file:
      - ./python-emotion-api/.env  # ✅ 이 줄을 추가하여 .env 파일을 읽도록 설정
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 5s
      timeout: 3s
      retries: 5

    #  frontend:
 #   build:
  #    context: ./frontend
   # container_name: frontend
#    ports:
 #     - "3000:80"
  #  depends_on:
   #   - backend

  #db:
  # image: mariadb:10.11
  #  container_name: mariadb
  # restart: always
  # ports:
  #   - "3306:3306"
  # environment:
  #   MARIADB_ROOT_PASSWORD: 1234
  #   MARIADB_DATABASE: moodiary
  #   MARIADB_USER: moodiary
  #   MARIADB_PASSWORD: moodiary
  #  volumes:
  #   - db_data:/var/lib/mysql

#volumes:
#  db_data:
