version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: maria
      MARIADB_DATABASE: moodiary_db
      MARIADB_USER: moodiary
      MARIADB_PASSWORD: moodiary
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  backend:
      build:
        context: ./backend
      container_name: moodiary_backend
      ports:
        - "8080:8080"
      depends_on:
        - mariadb
      environment:
        SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/moodiary_db
        SPRING_DATASOURCE_USERNAME: moodiary
        SPRING_DATASOURCE_PASSWORD: moodiary

volumes:
  db_data:

networks:
  app-network: