version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: moodiary
      MARIADB_DATABASE: moodiary_db
      MARIADB_USER: moodiary
      MARIADB_PASSWORD: moodiary
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/moodiary_db
      SPRING_DATASOURCE_USERNAME: moodiary
      SPRING_DATASOURCE_PASSWORD: moodiary
      EMOTION_API_URL: http://emotion-api:8000
    depends_on:
      - mariadb
      - emotion-api
    networks:
      - app-network

  emotion-api:
    build:
      context: ./python-emotion-api
    container_name: emotion-api
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
