version: "3.8"

services:
  springboot-app:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - moodiary-net

  fastapi-chatbot:
    build: ./chatbot
    ports:
      - "8000:8000"
    env_file:
      - ./chatbot/.env
    networks:
      - moodiary-net

networks:
  moodiary-net: