services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on: []

#  frontend:
 #   build:
  #    context: ./frontend
   # container_name: frontend
#    ports:
 #     - "3000:80"
  #  depends_on:
   #   - backend

  #db:
  # image: mariadb:10.11
  #  container_name: mariadb
  # restart: always
  # ports:
  #   - "3306:3306"
  # environment:
  #   MARIADB_ROOT_PASSWORD: 1234
  #   MARIADB_DATABASE: moodiary
  #   MARIADB_USER: moodiary
  #   MARIADB_PASSWORD: moodiary
  #  volumes:
  #   - db_data:/var/lib/mysql

#volumes:
#  db_data:
