version: "3.8"

services:
  springboot-app:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - moodiary-net

  fastapi-chatbot:
    build: ./chatbot
    ports:
      - "8000:8000"
    env_file:
      - ./chatbot/.env
    volumes:
      - faiss_volume:/app/faiss_data
    networks:
      - moodiary-net
volumes:
  faiss_volume:
  
networks:
  moodiary-net: